ALTER TABLE games
ADD COLUMN IF NOT EXISTS developers TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE games
ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE games
ADD COLUMN IF NOT EXISTS header_image_url TEXT;

ALTER TABLE games
ADD COLUMN IF NOT EXISTS metadata_updated_at TIMESTAMPTZ;
